- operation: Add
  participant_description:
    name: tinyBot_1
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: tinyBot_4
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: tinyBot_3
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: tinyBot_2
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: tinyRobot4
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.20000000000000001
        - 0.5
- operation: Add
  participant_description:
    name: tinyRobot5
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.20000000000000001
        - 0.5
- operation: Add
  participant_description:
    name: tinyRobot3
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.20000000000000001
        - 0.5
- operation: Add
  participant_description:
    name: tinyRobot1
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.20000000000000001
        - 0.5
- operation: Add
  participant_description:
    name: tinyRobot2
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.20000000000000001
        - 0.5